### ISSUE TITLE
[Request] AppleMilkTea

### ISSUE THREAD

**Issue by AegisLesha** [buttilda/Another-One-Bites-the-Dust#104]
I can has Jaw Crusher ore processing support pls???
I think it's quite easy to add, it's just another dust maker :3

**Comment by buttilda** [comment]
Too complicated. Their API isn't very versatile and I can't find anything in their code base XD
Doesn't help that the comments are all in japanese.

**Comment by karakufire** [comment]
although maybe you've known there, I wrote down it here [AppleMilkTea2](https://github.com/defeatedcrow/AppleMilkTea2_1.7.10)

**Comment by AegisLesha** [comment]
Have any idea @Glassmaker @defeatedcrow ?

**Comment by defeatedcrow** [comment]
What you asked me?
This issue has already been closed by the author. I don't want further request to the author.

I can be explained how to add the Jaw Crusher recipe. But the author  noted that my API have problems overall. Partial explanation seems to be insufficient for resolve.

I will not describe the Javadoc for the API in a language other than Japanese. Because it was created as modding sample for Japanese modders, it needs to described in Japanese.
