### ISSUE TITLE
Yellorite

### ISSUE THREAD

**Issue by slawr34** [buttilda/Another-One-Bites-the-Dust#15]
How would I go about including Yellorite processing in the configs?

**Comment by buttilda** [comment]
I'm not the one who chooses which ore gets added to the configs.
If the ore is in the game and is valid AOBD will find it.

The reason yellorite is not in the configs is because there's no ingotYellorite in the ore dictionary.

**Comment by slawr34** [comment]
Ah, I thought there was a way to manually add materials into the configs.

**Comment by buttilda** [comment]
There kind of is, say you needed a platinum dust to be produced as a sub product of the processing of Nickel... you could add that platinum dust using the config file.

But adding platinum processing without platinum being present in both ore and ingot form is not possible. Since AOBD searches for the suffixes, unless it finds orePlatinum and ingotPlatinum registered in the ore dictionary then it will not add processing for platinum.
Since the author of BigReactors adds oreYellorite and ingotYellorium, AOBD considers that to be two different metals and skips it.

I've spoken to the author of BigReactors and I think he will register oreYellorite as oreYellorium, which would allow AOBD to pick it up. If he doesn't do it soon enough, I'll add it myself to AOBD :3

**Comment by slawr34** [comment]
Quintupling Yellorite in a Mekanism setup just feels so right :P

**Comment by buttilda** [comment]
So yeah he added the change. yelorite ore will now be registered as oreYellorium as well as oreYellorite.
So this means AOBD will pick it up and allows quintupling it with mekanism :)

Sadly he said there's no ETA for the next release. So you'll have to keep checking :)
