### ISSUE TITLE
Different types of dust.

### ISSUE THREAD

**Issue by Staegrin** [buttilda/Another-One-Bites-the-Dust#31]
Not sure if it's your mod or not. I'm simply wondering if its intended for IC2 dust to be created in the SAG mill from ender IO and and pulverizer from Thermal expansion.
SAG mill:
Gold, iron, all ingots and obsidian will make the pulverized versions of the dusts. Including pulverized copper and tin. 
Copper ore, tin ore, lead and silver ore will produce  the IC versions.
Without AOBD installed only the thermal expansion versions are created from the ores.

Pulverizer:
All ores will produce the pulverized versions of the dusts. The by-products on the other hand, for ores your mod adds by-products for are all IC2 versions.
Examples
Aluminium has IC2 tin dust as a by-product
Ardite has IC2 gold dust as a by-product
Cobalt has IC2 iron dust as a by-product
Almost all of the nether ores give IC2 dusts in the pulverizer (this is most likely a problem with nether ores though because even without your mod this is still the case)

Thanks for the great mod and sorry to bug you with this.

**Comment by buttilda** [comment]
Yeah I'm aware of this issue, but unfortunately there isn't much I can do about it since each mod will prefer to use it's own items as outputs, and changing them all to one not always is possible (some mods don't allow changing existing recipes).

A workaround would be, if you use JABBA, to use the barrels to convert all of those items into one. If you insert a copper ingot from IC2 into a JABBA barrel and then insert a TE3 copper ingot, it will be automatically converted into IC2's one. I believe it works for dusts as well.
