### ISSUE TITLE
Ex Nihilo And Ex Astris Rebirth support

### ISSUE THREAD

**Issue by claybiockiller** [buttilda/Another-One-Bites-the-Dust#73]
Dear Gany,
I think those ore gravels, sands and dusts from Ex Nihilo and Ex Astris Rebirth should be supported by AOBD. And I think add those special ore blocks into ore dictionary is hazardous because playesr can use divices like Unifier in MFR to turn those special ore blocks into normal ones and use hammer or automatic hammerer to get more special ore blocks.
Clayblockiller

**Comment by buttilda** [comment]
Last time I looked into it, I couldn't add support because none of the blocks/items added by ExNihilo are registered in the ore dictionary and AOBD works on the premisse that things it's adding support to are registered. I'll check it out again and see if it's changed, and maybe even do some tweaks myself so that support can be added.
I can see how useful it would be :3

**Comment by buttilda** [comment]
Closing because of #92
